### ISSUE TITLE
How to remove line numbers?

### ISSUE THREAD

**Issue by ffgg11** [apoorvkh/cvpr-latex-template#1]

**Comment by apoorvkh** [comment]
You can remove line numbers by setting `\arxiv` OR `\camera` in [line 2 of `_main.tex`](https://github.com/apoorvkh/cvpr-latex-template/blob/main/_main.tex#L2), instead of `\review`.

**Comment by ffgg11** [comment]
> You can remove line numbers by setting `\arxiv` OR `\camera` in [line 2 of `_main.tex`](https://github.com/apoorvkh/cvpr-latex-template/blob/main/_main.tex#L2), instead of `\review`.

Thanks! Your method works.
