### ISSUE TITLE
Do you plan to update for cvpr 2023?

### ISSUE THREAD

**Issue by pcicales** [apoorvkh/cvpr-latex-template#2]
Let me know if I can help you do it in any way.

**Comment by apoorvkh** [comment]
So simple! I've updated it for 2023 with this commit: 47ecc6af49aefa8e2933f34d4187aff636076fa0

FYI, here was the diff between relevant files in the 2022 and 2023 author submission kits.

```
diff cvpr2022-author_kit-v1_1-1/latex/PaperForReview.tex cvpr2023-author_kit-v1_1-1/latex/PaperForReview.tex
1c1
< % CVPR 2022 Paper Template
---
> % CVPR 2023 Paper Template
42c42
< \def\confYear{2022}
---
> \def\confYear{2023}
```

**Comment by pcicales** [comment]
@apoorvkh thanks a lot! Yeah I should have checked their similarity, I didn't realize the templates didn't change at all :)
