### ISSUE TITLE
How to insert full width figure

### ISSUE THREAD

**Issue by ShunchiZhang** [apoorvkh/cvpr-latex-template#3]
E.g.: Figure 5 in [High-Resolution Image Synthesis with Latent Diffusion Models (Rombach et al., CVPR 2022)](https://arxiv.org/abs/2112.10752)

Thank you so much!

<img width="963" alt="image" src="https://user-images.githubusercontent.com/81918723/197409740-03dede15-3f91-4149-9391-404f4381702b.png">

**Comment by apoorvkh** [comment]
No problem at all! It's a good question. I'll leave it here in case anyone else was wondering the same.
