### ISSUE TITLE
Referencing Appendix from Main Document in \review Mode

### ISSUE THREAD

**Issue by GeorgeCazenavette** [apoorvkh/cvpr-latex-template#6]
Hello :)

Is there a way to make references to the appendix/supplement from the main document while in \review mode?

I can only seem to get it to work by commenting out the \ifarxiv block, but this causes the appendix to also render.

Thanks!

**Comment by apoorvkh** [comment]
Hey, you can use the `\supp` macro to automatically inject the text "supplemental material" (for `\review` or `\cameraready` modes) or "appendix" (for `\arxiv` mode).

But I think you are actually asking to do something like `\cref{sec:appendix_section}` within the main body. That's a good idea! I just pushed a change to support that. The section will be referred to as "App. A" or "Supp. A" (following the condition above). Let me know if that sounds good!

**Comment by GeorgeCazenavette** [comment]
This is perfect! Thanks so much :)
