### ISSUE TITLE
Wrong bibliographystyle file reference.

### ISSUE THREAD

**Issue by haowang-cqu** [apoorvkh/cvpr-latex-template#7]
https://github.com/apoorvkh/cvpr-latex-template/blob/474932adb79932044059d0663c3c1a73d98fc7b9/_supplementary.tex#L19

should be

```
 \bibliographystyle{ieeenat_fullname} 
```

**Comment by apoorvkh** [comment]
Thanks for catching that! I've corrected it in f3cc85dc9a6bfd12f90bb90ac66eee06a9c0d902.
