### ISSUE TITLE
Left and Right margins not same width

### ISSUE THREAD

**Issue by GeorgeCazenavette** [apoorvkh/cvpr-latex-template#8]
Hello again :)

I was losing my mind trying to center a figure properly when I realized that the left and right margins aren't the same size (right margin is larger).

This happens both in review and arxiv modes.

Do you have any idea what could be causing this?

Thanks!

![image](https://github.com/apoorvkh/cvpr-latex-template/assets/18726777/04d1c427-17d7-431e-8b03-d7dfd4f670db)

**Comment by GeorgeCazenavette** [comment]
I feel like I remembering this happening in the past, but I don't remember how I fixed it.

This is more of an ask for your latex knowledge rather than an issue with the repo :)

**Comment by apoorvkh** [comment]
Hey, you have a very keen eye! It looks like these margins are a design choice of the official CVPR template. If I were to guess, maybe it is to allow more space for handwritten notes on the right-hand margin?

So, I wouldn't recommend altering this. That said, I don't think the submission guidelines have a restriction on the left and right page margins (as long as you don't change the combined width of the columns). So you are free to modify this at your own risk.

I think you can set this variable to approx. `-0.2in`.

https://github.com/apoorvkh/cvpr-latex-template/blob/f3cc85dc9a6bfd12f90bb90ac66eee06a9c0d902/cvpr.sty#L367

You could probably refine that number further. Either try to understand the `cvpr.sty` source code or do it by eye, like I did. I found this package helpful for displaying guidelines:

```latex
\usepackage[
  grid,
  gridcolor=red!50,
  subgridcolor=green!50,
  gridunit=in
]{eso-pic}
```

Hope that helps!

**Comment by apoorvkh** [comment]
Actually, here is a more plausible explanation, with slightly better margin values: https://github.com/MCG-NKU/CVPR_Template/issues/18#issuecomment-1949924031
